[build]
builder = "NIXPACKS"
buildCommand = """
composer install --no-dev --optimize-autoloader
npm install
npm run build
php artisan optimize
php artisan optimize:clear
"""

[start]
command = "php artisan serve --host=0.0.0.0 --port=$PORT"
